language: php
sudo: false

php:
    - 7.1
    - 7.2
    - 7.3

install: travis_retry composer install
script: echo 'OK' #no phpunit currently... see #8

stages:
    - Static Analysis

jobs:
    include:
        - stage: Static Analysis
          script: vendor/bin/phpstan analyze

cache:
    directories:
        - $HOME/.composer/cache
