name: CI

on:
  push:
    branches:
      - master
      - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  pull_request: ~

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: PHPStan
      run: vendor/bin/phpstan analyze
