name: Continuous Integration

on:
  push:
    branches:
      - master
      - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  pull_request: ~

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
          php-version: '7.3'
          coverage: none
          tools: composer:v2, psalm

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress --ansi

    - name: Psalm
      run: psalm --output-format=github --shepherd
